salsa-telescope/salsa

.gitignore
Cargo.lock
backend/Cargo.toml
backend/src/booking_routes.rs
backend/src/database.rs
backend/src/main.rs

The database consists of a json-file protected behind an RwLock. Will almost certainly need to be changed into a real database at some point but this is good for now.
The database is generic over the stored type so can be used for storing more/other things in the future.
For better ergonomics when developing, I need to add a fallback if the database file is missing. That's why this is marked as a draft PR.

Add simple bookings "database"

---

backend/src/booking_routes.rs
backend/src/database.rs
backend/src/main.rs

I added support for multiple keys in the "database". I am planning to move the telescope configurations into the "database". Does this change make sense with your design? Or does it break some intended use case?
I know I killed the cache. Sorry! It got tricky to get right and the performance impact should be relatively small. It should be possible to make a CachedFileStorage but that will result in multiple layers of locks.

Add support for multiple keys in database

---

Cargo.toml

Rust edition 2021 defaults to and requires resolver version 2. Since we use a virtual workspace for the project we don't set a Rust edition. The resolver used is determined in the workspace so we need to set the version explicitly.

Set resolver version to 2 in workspace

---

backend/src/main.rs
backend/src/salsa_telescope.rs
backend/src/telescope_controller.rs
backend/src/telescope_routes.rs
backend/src/telescope_tracker.rs

We want to achieve two things:
- Shrinking SalsaTelescope which is getting big
- More intuitive updating of telescope controller state and tracking
To do this we take out the parts relating to the telescope controller from SalsaTelescope. The SalsaTelescope remains as a facade but can in the future be broken up further.
By using a long lived task to do all communication to with one telescope controller we prepare for using less large locks in the future. Updating the telescope continuously (e.g while tracking) is moved into this task. This allows other parts of the system to send commands and observe the effects on the telescope without having to continuously drive it.

Extract TelescopeController from SalsaTelescope

---

.github/workflows/rust.yml

apt-get install complained that it couldn't fetch some packages during the "Install libuhd" step. A quick apt update seems to fix that problem.

Fix github workflow

---

Cargo.toml

If FFT is too slow then we need to find a proper solution (e.g break into own crate that is optimized or something). Always having optimized builds is too hard to debug.

Don't run optimized builds for dev/debug

---

src/observe_routes.rs
templates/index.html

- Push the observe url to history when navigating. Enables refresh and back button.
- Enable rendering observe inside of index template as well as as a fragment for insertion into the document by htmx.

Push observe url on navigation

---

src/fake_telescope.rs
src/observe_routes.rs
src/telescope_tracker.rs
src/telescopes/mod.rs

Don't use abbreviations, prefer to use the full names.

Use full names for coordinate system components

---

src/observe_routes.rs
templates/observe.html
templates/telescope_state.html

If the telescope state is it's own template it can be rendered and updated via htmx by itself. It can also be reused to show the telescope state on the welcome page.

Extract telescope state into it's own template

---

src/observe_routes.rs
src/telescope_routes.rs
templates/observe.html

Put a div on the page and put any errors into the div.
It will not quite work if no page with an error box has ever been rendered. This will require some further reworking.
Part of the error handling here could be extracted to deal with errors that occur elsewhere.

Implement error handling in observe

---

src/observe_routes.rs
src/salsa_telescope.rs
src/telescope.rs
src/telescope_api_routes.rs
src/telescope_routes.rs

Easier to just use an async API through an owned handle to an underlying telescope collection.

Hide telescope collection locks from client

---

src/observe_routes.rs
templates/observe.html

It wasn't working. Let's do tracking by default. If the user wants to stop tracking they can press park (although park isn't implemented yet).

Remove tracking toggle from observe

---

templates/index.html

We don't need a separate make booking now so let's remove it.
We also don't need weather on the navbar.

Remove make booking and weather from navbar

---

tests/test.rs

The code demonstrates how to run a binary in a test as well as how to shut it down.
This test is mostly a placeholder and a start for further tests.

Add start and stop backend test

---

src/observe_routes.rs
templates/index.html
templates/observe.html

Use `observe/<telescope id>` to select which telescope to use for observation. This required some random updates to not break other things.
The _Observe_ link in the navbar is now pointed to `observe/fake` to keep the same behavior. Other telescopes are only available through changing the path directly in the browser.

Set telescope to observe through from path

---

src/bookings/routes.rs
templates/bookings.html

No point in being able to create a booking in the name of someone else.
Or, of course there is some point, but it's not really reasonable!

Create bookings as the logged in user

---

src/telescope_routes.rs

Helpful to get some info about what's going on the backend for debugging purposes.

Add debug log for measurement websocket

---

assets/observe_chart.js
development/database.json

The measurement websocket URL is extracted from the current window.location instead of hardcoding to `fake`. This makes it possible to observe a spectrum with a real telescope.
Also change `fake` to two fake telescopes: `fake1` and `fake2`. Having two different ones is helpful for testing out telescope selection logic.

Fix measurement websocket to wrong telescope

---

src/models/telescope.rs
src/routes/booking.rs
templates/bookings.html

Through the frontend an empty telescope id could be provided or a request could come in with an unknonw id. Just reject the booking with code 400 if this happens.
Fixes #174.

Only allow bookings for existing telescopes

---

src/models/salsa_telescope.rs
src/models/session.rs
src/routes/telescope.rs

We accept the lint to prefer `is_multple_of` over directly using modulus `%`. This _is_ clearer, and it never panics.

Fix clippys

---

templates/bookings.html

You can see which are your own bookings by looking under _My bookings_ and we don't want to leak the usernames of other users.
Closes #171.

Don't display user for bookings
