salsa-telescope/salsa

.github/workflows/rust.yml

Add github action to project

---

Cargo.lock
backend/Cargo.toml
backend/src/booking_routes.rs
backend/src/main.rs
common/Cargo.toml
common/src/lib.rs
frontend/Cargo.toml
frontend/src/main.rs
frontend/src/pages/bookings.rs
frontend/src/pages/mod.rs
frontend/src/pages/welcome.rs

These are only the first baby steps towards a booking system. Here are som of the major points that need to be expanded upon:
- Frontend only shows a list of bookings instead of a calendar view or whatever we want there.
- Backend always sends the same static list of hard coded bookings instead of querying a database.
- Definition of a booking is too simplistic, we probably don't want user name and telescope to be strings.
Still, it is a start! =)

Add bookings list

---

backend/src/main.rs
backend/src/salsa_telescope.rs
common/src/coords.rs
frontend/src/pages/observe.rs

Works to run brage! Some issues, but it runs! :)

Working brage test code

---

Cargo.lock
backend/Cargo.toml
backend/src/fake_telescope.rs
backend/src/salsa_telescope.rs
uhd_test/Cargo.toml
uhd_test/src/main.rs

Remove last references to astro crate so it's no longer needed.

Really remove astro

---

uhd_test/Cargo.toml
uhd_test/src/main.rs

Managed to already commit these changes by mistake in the "remove_astro" merge so might as well merge this too.

Measure switched

---

backend/src/fake_telescope.rs
backend/src/salsa_telescope.rs
common/src/coords.rs
frontend/src/pages/bookings.rs
frontend/src/pages/telescope.rs

* Fix the unit tests
* Inject time in coordinate transformations to ensure tests are stable

Switch internal angle representation from degrees to radians

---

backend/src/salsa_telescope.rs

Use take to avoid using references to self.active_integration. Copying the value out and then putting it back in (if it can't be optimized out) is cheap since ActiveIntegration doesn't hold very much data.

Remove unwraps from ex-fulbool code

---

backend/src/booking_routes.rs
backend/src/database.rs
frontend/src/pages/bookings.rs

- End point for adding a new booking.
- Form for adding a booking
- New API: `DataBase.update_data()` for mutating the contents of the data base.

Booking form

---

Cargo.lock
Cargo.toml
development/database.json
fakesalsa/Cargo.toml
fakesalsa/src/main.rs

This sauce is not quite real.
To test the backend we can use a fake Salsa telescope controller talking over TCP.
This PR should add basic functionality so that some function can be tested end-to-end. More functionality can be added in later PRs.

Fake Salsa telescope controller

---

backend/src/booking_routes.rs
common/src/lib.rs
frontend/src/pages/make_booking.rs

Don't allow creating booking conflicts.

Booking conflicts

---

frontend/src/components/mod.rs
frontend/src/components/notification_area.rs
frontend/src/pages/make_booking.rs
frontend/style.css

Specifically the results of the API call to create a booking is shown in a notification area in the frontend.

Show fetch results in frontend

---

frontend/index.html
frontend/src/components/mod.rs
frontend/src/components/navbar.rs
frontend/src/main.rs
frontend/src/pages/bookings.rs
frontend/src/pages/make_booking.rs
frontend/src/pages/observe.rs
frontend/src/pages/telescope.rs
frontend/src/pages/weather.rs
frontend/src/pages/welcome.rs
frontend/style.css

I have been working on a design for the frontend. It is neither perfect, nor complete, but I think it looks pretty good, and then we can change and improve stuff along the way.
Tell me what you think! =)

Frontend design

---

Cargo.toml
src/bookings/api_routes.rs
src/bookings/routes.rs
src/coords.rs
src/fake_telescope.rs
src/main.rs
src/salsa_telescope.rs
src/telescope_api_routes.rs
src/telescope_routes.rs
src/telescope_tracker.rs
src/telescopes/mod.rs
src/weather.rs

Update to Rust edition 2024

---

src/index.rs
templates/index.html

This is a preparation for rendering pages as fragments for htmx updates of as complete pages.

Render index completely on server side

---

src/observe_routes.rs
templates/observe.html

Post new target in observe

---

src/main.rs
src/observe_routes.rs
src/telescope.rs
src/telescope_routes.rs
templates/observe.html

- Move telescope state into telescope routes.
- In observe poll the telescope state every 1 s.

Continuously update telescope state in observe

---

src/observe_routes.rs
src/telescope.rs
src/telescope_api_routes.rs
src/telescope_routes.rs

Make more ergonomic and less error-prone by not exposing synchronization primitives to the client code.

Hide telescope locks from client

---

src/observe_routes.rs

We no longer keep any long-lived telescope locks in the client code. Thus there is no need to take any extra care to avoid deadlocks. Just await away on various properties.

Remove deadlock prevention from observe

---

src/observe_routes.rs
templates/observe.html

Implement park button in observe

---

Cargo.lock
Cargo.toml
assets/observe_chart.js
src/observe_routes.rs
src/telescope_routes.rs
src/telescopes/mod.rs
templates/observe.html

We want to be able to see the observed spectrum in the observe UI.
Pieces:
- D3 frontend
- Transport of spectrum over websockets
- Serialization/deserializaton

Use D3 to observe spectrum

---

readme.md

Useful references for development. To be replaced with updated documentation as that is created.

Add links to old documentation

---

src/authentication.rs
src/bookings/routes.rs
src/index.rs
src/main.rs
src/observe_routes.rs
templates/index.html

We can now be a (hardcoded) user. To be filled in with authentication stuff so we can be a real user. Also to be used for showing the right things depending on user and allowing the right actions depending on user.

Add dummy authentication middleware

---

src/authentication.rs
src/bookings/routes.rs
templates/bookings.html

It's kinda nice to see your own bookings.

Show My bookings on Bookings page

---

development/database.json
src/coords.rs
src/fake_telescope.rs
src/observe_routes.rs
src/telescope_controller.rs
src/telescope_tracker.rs
src/telescopes/mod.rs
templates/observe.html
templates/telescope_state.html

- Add horizontal coordinate system to target selection.
- Remove Stopped as target type

Improve coordinate systems

---

assets/style.css
src/bookings/routes.rs
templates/bookings.html

Make it so you can get to the observe UI from booking if the booking is currently active.

Link to observe from booking if active

---

templates/index.html

Remove broken observe-link from navbar

---

src/telescope_routes.rs

Not needed right now so let's make things simpler.

Remove telescope API routes

---

src/fake_telescope.rs
src/salsa_telescope.rs
src/telescope.rs
src/telescope_tracker.rs

Remove unused functions from telescope

---

.gitignore
Cargo.lock
Cargo.toml
sql_migrations/V1__add_user_table.sql
src/authentication.rs
src/database.rs
src/main.rs
templates/create_user.html
templates/index.html
templates/welcome_user.html

Use the oauth2 crate to get user identity from Discord.
Not integrated quite yet.
Other providers/sources should be added later.

Add flow for Discord authentication

---

src/authentication.rs
src/bookings/routes.rs
src/error.rs
src/index.rs
src/main.rs
src/observe_routes.rs
src/user.rs

Create a model module that does the database talking and such.

Extract user creation/fetching from authentication

---

src/observe_routes.rs
templates/observe.html

Split track and observe buttons

---

src/authentication.rs

Make sure CSRF token is valid in the Discord Oauth2 flow. This ensures that the login request originated from Salsa and not anywhere else.
Closes #152.

Validate CSRF token when coming back from Discord

---

src/authentication.rs

Delete leftover debug logging

---

src/database.rs
src/observe_routes.rs
src/salsa_telescope.rs
src/telescopes/mod.rs

Fix clippys (all of them)

---

src/routes/observe.rs

Remove some old hardcoding in observe.

Fix hardcoding in errors in observe

---

src/models/booking.rs
src/routes/booking.rs
src/routes/telescope.rs
tests/http_tests.rs

Check active booking before upgrading to websocket
